In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
x = dataset.drop(labels = ['RowNumber', 'CustomerId', 'Surname','Exited'],axis=1)
y = dataset['Exited']

In [5]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder


In [8]:
label_1 = LabelEncoder() # encoding geographies

In [9]:
x['Geography'] = label_1.fit_transform(x['Geography'])

In [10]:
label_2 = LabelEncoder() #encoding genders

In [11]:
x['Gender'] = label_2.fit_transform(x['Gender'])

In [12]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
one = OneHotEncoder(handle_unknown='ignore')

In [15]:
x['Geography']

0       0
1       2
2       0
3       0
4       2
       ..
9995    0
9996    0
9997    0
9998    1
9999    0
Name: Geography, Length: 10000, dtype: int32

In [16]:
x = pd.get_dummies(x,drop_first=True,prefix =['Geogrpahy'],columns = ['Geography'] )

In [48]:
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geogrpahy_1  Geogrpahy_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

### Feature Standardization

In [49]:
from sklearn.preprocessing import StandardScaler

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify = y)

In [58]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [60]:
x_train

array([[ 0.54832394,  0.90521949, -0.66439377, ..., -0.76364728,
        -0.57927478, -0.57946723],
       [ 0.7750281 , -1.10470445, -0.66439377, ...,  0.66805417,
        -0.57927478,  1.72572313],
       [ 0.2391819 , -1.10470445,  0.09970264, ..., -0.31980462,
        -0.57927478, -0.57946723],
       ...,
       [-1.44048981, -1.10470445,  1.05482315, ..., -1.32879897,
         1.72629647, -0.57946723],
       [-0.16270274,  0.90521949, -0.47336966, ..., -1.01467073,
        -0.57927478, -0.57946723],
       [-0.16270274,  0.90521949, -0.47336966, ..., -0.66361337,
        -0.57927478,  1.72572313]])

### Build ANN

In [52]:
model = Sequential()
model.add(Dense(x.shape[1],activation = 'relu'))
model.add(Dense(128,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [53]:
model_2 = Sequential()
model_2.add(Dense(x.shape[1],activation = 'relu'))
model_2.add(Dense(256,activation = 'relu'))
model_2.add(Dense(1,activation = 'sigmoid'))

In [54]:
model_2.compile(optimizer='adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [55]:
model_2.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 1s 167us/sample - loss: 0.4265 - accuracy: 0.8249
Epoch 2/10
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3634 - accuracy: 0.8516
Epoch 3/10
8000/8000 [==============================] - 1s 130us/sample - loss: 0.3472 - accuracy: 0.8551
Epoch 4/10
8000/8000 [==============================] - 1s 133us/sample - loss: 0.3403 - accuracy: 0.8601
Epoch 5/10
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3373 - accuracy: 0.8599
Epoch 6/10
8000/8000 [==============================] - 1s 144us/sample - loss: 0.3351 - accuracy: 0.8626
Epoch 7/10
8000/8000 [==============================] - 1s 132us/sample - loss: 0.3323 - accuracy: 0.8643
Epoch 8/10
8000/8000 [==============================] - 1s 136us/sample - loss: 0.3310 - accuracy: 0.8606
Epoch 9/10
8000/8000 [==============================] - 1s 135us/sample - loss: 0.3302 - accuracy: 0.8620
Epoch 10/10
8000/8000 [=

In [25]:
model_2.evaluate(x_test,y_test.to_numpy())

2000/2000 [==============================] - 0s 70us/sample - loss: 0.3926 - accuracy: 0.8410


[0.39262290358543395, 0.841]

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
y_pred = model_2.predict_classes(x_test)

In [28]:
confusion_matrix(y_test,y_pred)

array([[1499,   94],
       [ 224,  183]], dtype=int64)

In [29]:
accuracy_score(y_test,y_pred)

0.841

### Ploting Learning Curve and Confusion Matrix

In [33]:
y = dataset['Exited']

In [35]:
y.to_numpy()

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [36]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [39]:
x_train

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
5709          644       0   39       9       0.00              1          1   
1397          487       0   46       4  135070.58              2          1   
7125          746       0   32       4       0.00              2          1   
9386          717       0   33      10  102185.42              2          1   
5449          549       0   46       7       0.00              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
2731          670       0   33       7       0.00              2          1   
1881          530       0   36       2       0.00              2          1   
2826          693       0   43       4  152341.55              1          1   
2394          543       1   43       9       0.00              2          1   
5651          521       0   61       0  125193.96              1          1   

      IsActiveMember  EstimatedSalary  Geogrpahy_1  Geogrpahy_2  
5709               0          3740.93            0            0  
1397               1         44244.49            1            0  
7125               1         72909.75            0            0  
9386               0         23231.93            1            0  
5449               1        109057.56            0            0  
...              ...              ...          ...          ...  
2731               1         88187.81            0            0  
1881               1         14721.80            0            1  
2826               0          9241.78            0            0  
2394               1         78858.07            0            0  
5651               1        109356.53            1            0  

[8000 rows x 11 columns]