### Intro to Tensor flow Programming

In [8]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [9]:
tf.__version__


'2.1.0'

In [10]:
a = tf.constant("hello")
b = tf.constant("world")

In [12]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [14]:
print(result)

b'helloworld'


In [15]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [17]:
with tf.Session() as sess:
    result = sess.run(var1+var2)

In [18]:
print(result)

40


In [19]:
mat_1 = tf.fill((5,5),10)

In [20]:
zeros = tf.zeros((5,5))

In [21]:
ones = tf.ones((5,5))

In [22]:
randn = tf.random_normal((4,4),mean = 0, stddev=1)

In [23]:
 randu = tf.random_uniform((4,4),minval=0,maxval=1)

In [24]:
myops = [mat_1,zeros,ones,randn,randu]

In [25]:
sess = tf.InteractiveSession()

In [26]:
for op in myops:
    print(sess.run(op))
    print("\n")

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 1.3521545  -0.56944185  0.5360016   0.6208839 ]
 [ 0.452965   -0.8030009  -1.0029043  -1.1206154 ]
 [ 0.5057326   0.52321756 -0.14251761  0.7113847 ]
 [ 0.8345632  -0.92466336 -1.4760873  -0.3698711 ]]


[[0.7820076  0.36398304 0.0842551  0.88025236]
 [0.87033856 0.50649536 0.46029472 0.56427145]
 [0.0932169  0.7917136  0.2827965  0.59712267]
 [0.5222273  0.21664369 0.15541291 0.55588174]]




In [28]:
sess.run(op)

array([[0.6384876 , 0.8730602 , 0.55741274, 0.46109378],
       [0.01353753, 0.50205696, 0.24138618, 0.54006135],
       [0.3529154 , 0.6004145 , 0.81327605, 0.41592085],
       [0.13496172, 0.16644466, 0.23505878, 0.8268461 ]], dtype=float32)

In [30]:
a= tf.constant([[4,5],[8,6]])

In [31]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [32]:
b = tf.constant([[10],[50]])

In [33]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a,b)

In [37]:
sess.run(result)

array([[290],
       [380]])

### Exersice 2

In [38]:
var1 = tf.constant(10)
var2 = tf.constant(20)

In [39]:
var3 = var1 +var2

In [40]:
with tf.Session() as sess:
    result = sess.run(var3)

In [41]:
print(result)

30


In [42]:
print(var3)

Tensor("add_2:0", shape=(), dtype=int32)


In [43]:
print(tf.get_default_graph)

<function get_default_graph at 0x000001D2D2F9B8B8>


### Exercise 3

In [44]:
#variables and place holder


In [49]:
tf.InteractiveSession.close(sess)


In [61]:
sess = tf.InteractiveSession()

In [62]:
my_tensor = tf.random_uniform((5,5),0,2)

In [64]:
print(sess.run(my_tensor))

[[0.30217838 0.63575053 1.0190799  1.1539688  0.6420083 ]
 [1.9395063  1.6651638  0.10905671 0.22139573 1.9422762 ]
 [0.568295   0.772928   0.16611624 0.39602876 1.9421713 ]
 [1.9832637  0.2810812  1.5217302  1.9412324  0.34357333]
 [1.6691506  0.42268825 1.8543906  1.6608381  0.12324905]]


In [65]:
var1 = tf.Variable(my_tensor)

In [68]:
#sess.run(var1)
init = tf.global_variables_initializer()

In [69]:
sess.run(init)

In [70]:
sess.run(var1)

array([[1.4973435 , 1.012502  , 0.9383688 , 0.5035293 , 1.2847311 ],
       [0.18863893, 1.5132256 , 0.4700203 , 1.4566374 , 0.95521903],
       [0.6333804 , 0.9755535 , 1.3269725 , 1.3926418 , 1.0298789 ],
       [0.59133005, 1.729011  , 0.19289303, 0.4008057 , 0.24570656],
       [1.2210305 , 1.8916619 , 0.87286425, 1.7836466 , 0.41564488]],
      dtype=float32)

In [71]:
#place holder

In [72]:
pH = tf.placeholder(tf.float32, shape = (4,4))

In [73]:
ph2 = tf.placeholder(tf.float32)

### Exercise 4

In [74]:
import numpy as np

In [75]:
np.random.seed(101)
tf.set_random_seed(101)

In [76]:
rand_a = np.random.uniform(0,100,(5,5))

In [90]:
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [93]:
 rand_b = np.random.uniform(0,100,(5,5))

In [94]:
rand_b


array([[20.91614989, 65.99245189, 52.96233988, 74.85203699,  9.37568559],
       [78.452185  , 68.72420376, 69.50784965, 49.68665196, 97.5361127 ],
       [20.35276206, 29.90204097, 22.76558928,  4.81688854, 90.39713575],
       [ 8.01035387, 60.72162718, 63.08467036, 37.79419319,  1.32410111],
       [84.22194119, 38.49377461, 55.16658451, 71.05381401, 67.52788507]])

In [80]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [96]:
add = a+b
mul = a*b

In [83]:
with tf.Session() as sess:
    add_result = sess.run(add,feed_dict = {a:20,b:30})
    print(add_result)
    

50.0


In [99]:
with tf.Session() as sess:
    add_result = sess.run(a+b,feed_dict = {a:rand_a,b:rand_b})
    print(add_result)
    print('\n')
    mult = sess.run(a*b,feed_dict = {a:rand_a,b:rand_b})
    print(mult)
    

[[ 72.556015 123.05921   55.809765  92.0042    77.90338 ]
 [161.84187   99.42083  158.86916  121.84104  116.53001 ]
 [ 75.77552   65.115234  40.954826  83.37706  186.94547 ]
 [ 31.24572   69.07777  123.439514 110.69347   28.947983]
 [152.75256   90.28052   60.015038  84.840744  86.224625]]


[[1080.107    3765.9753    150.80617  1283.8745    642.49414 ]
 [6542.103    2109.601    6211.3125   3585.11     1852.5906  ]
 [1128.0062   1052.9464    414.08875   378.4156   8727.691   ]
 [ 186.12352   507.3986   3807.4653   2755.1694     36.576813]
 [5771.7827   1993.4674    267.47263   979.6135   1262.5515  ]]


### Exercise 5

In [101]:
n_f = 10
n_d_n = 3

In [102]:
x = tf.placeholder(tf.float32,(None,n_f))

In [103]:
b = tf.Variable(tf.zeros(n_d_n))

In [104]:
w = tf.Variable(tf.random_normal([n_f,n_d_n]))

In [105]:
#y = mx+c
xw = tf.matmul(x,w)

In [106]:
z = tf.add(xw,b)
a = tf.sigmoid(z)

In [107]:
#Variable
init = tf.global_variables_initializer()

In [109]:
with tf.Session() as sess:
    sess.run(init)
    
    layer_out = sess.run(a,feed_dict ={x:np.random.random([1,n_f])} )

In [110]:
print(layer_out)

[[0.8189372  0.87473875 0.21973088]]
